name: ProjectTests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas sqlalchemy pytest kaggle

      - name: Set up Kaggle API
        env:
          KAGGLE_CONFIG_DIR: $HOME/.config
        run: |
          mkdir -p $KAGGLE_CONFIG_DIR
          cp /path/to/kaggle.json $KAGGLE_CONFIG_DIR/

      - name: Run tests
        run: |
          python3 -m unittest discover -s ./project -p "test.py"
