name: Project Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USER_NAME: ${{ secrets.KAGGLE_USER_NAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./project/requirements.txt

    # Step 4: Set Kaggle Credentials
    - name: Set Kaggle Credentials
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USER_NAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json 

    # Step 5: Run the Python pipeline
    - name: Run Pipeline
      run: |
        python ./project/pipeline.py

    # Step 6: Run Tests
    - name: Run Tests
      run: |
        chmod +x ./project/tests.sh
        ./project/tests.sh

    # Step 7: Lint and Code Quality Checks (Optional)
    - name: Lint Code
      run: |
        pip install flake8
        flake8 ./project --count --select=E9,F63,F7,F82 --show-source --statistics
